
name: 'budget_dbt'
version: '1.0.0'

profile: 'budget_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:   # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  budget_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:

  # Keywords by category to use for Revolut categorisation
  categories:

    donation:
      - charity
      - fund
      - appeal
      - trust
      - foundation

    entertainment:
      - theatre
      - museum
      - cathedral
      - arena
      - stadium
      - concert
      - festival
      - cinema
      - gallery
      - castle
      - distillery

    groceries:
      - butcher
      - market
      - bakery

    health:
      - dental
      - pharmacy
      - clinic
      - optician
      - apothecary
      - wellness
      - fitness
      - gym
      - medical
      - vitamin

    income:
      - payment from
      - salary
      - wage
      - pension
      - refund
      - payment
      - commission

    interest:
      - interest
      - dividend
      - yield
      - returns

    pubs:
      - bar
      - pub
      - lounge
      - club
      - tavern
      - inn
      - brewery

    restaurants:
      - coffee
      - food
      - bistro
      - café
      - cafe
      - restaura
      - grill
      - pizz
      - diner
      - eatery
      - takeaway

    transfers:
      - transfer
      - exchange
      - wire
      - deposit
      - withdraw

    travel:
      - bus
      - air
      - rail
      - train
      - hotel
      - ferry
      - taxi
      - booking
      - transport
      - shuttle
      - ride
      - rental
      - airport
      - cruise
      - reservation

    cash:
      - cash

    utilities:
      - energ
      - electric
      - utilit
      - water
      - internet
