
name: 'budget_dbt'
version: '1.0.0'

profile: 'budget_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:   # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  budget_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  # Keywords by category to use for Revolut categorisation
  categories:
    cash: ['cash']
    donation: ['foundation']
    entertainment: ['theatre', 'museum', 'cathedral']
    groceries: ['butcher']
    health: ['dental', 'pharmacy']
    income: ['payment from']
    interest: ['interest']
    pubs: ['bar', 'pub', 'lounge', 'club']
    restaurants: ['coffee', 'food', 'bistro', 'café', 'cafe', 'restaura', 'grill', 'pizz', 'tavern', 'diner']
    transfers: ['transfer', 'exchange to']
    travel: ['bus', 'air', 'rail', 'train', 'hotel', 'ferry', 'taxi']
