budget_dbt:
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: etl.db
      schema: 'main'
      schemas_and_paths:
        main: 'db/etl.db'
      schema_directory: '/db'
      # optional: list of file paths of SQLite extensions to load. see README for more details.
      extensions:
        - "{{ env_var('USERPROFILE') }}/.sqlpkg/nalgeon/crypto/crypto.dll"
        - "{{ env_var('USERPROFILE') }}/.sqlpkg/nalgeon/regexp/regexp.dll"

  target: dev
