budget_dbt:
  outputs:

    dev:
      type: duckdb
      threads: 4
      database: etl
      schema: 'main'
      path: 'db/etl.duckdb'
      # DuckDB specific settings
      settings:
        memory_limit: '2GB'
        temp_directory: 'db/temp'

  target: dev
