budget_dbt:
  outputs:

    dev:
      type: duckdb
      path: 'db/etl.duckdb'
      database: 'etl'
      threads: 24
      extensions:
        - "httpfs"
        - "json"
        - "icu"
    local:
      type: duckdb
      path: 'db/local.duckdb'
      database: 'local'
      threads: 24
      extensions:
        - "httpfs"
        - "json"
        - "icu"

