version: 2

sources:
  - name: bofa
    database: "{{ 'local' if target.name == 'local' else 'etl' }}"
    schema: main
    tables:
      - name: raw_bofa__activity
        description: Raw transaction data from Bank of America.
        columns:
          - name: Date
            description: The date of the transaction.
            tests:
              - dbt_utils.not_empty_string
              - dbt_utils.expression_is_true:
                  expression: "try_strptime(date, '%m/%d/%Y') is not null"
          - name: Amount
            description: The amount of the transaction.
            tests:
              - dbt_utils.not_empty_string
          - name: "Original Description"
            description: The original description of the transaction.
            tests:
              - dbt_utils.not_empty_string
          - name: "Simple Description"
            description: A simplified description of the transaction.
          - name: Category
            description: The category of the transaction.
          - name: "Account Name"
            description: The name of the account.
            tests:
              - dbt_utils.not_empty_string
          - name: Status
            description: The status of the transaction.
            tests:
              - dbt_utils.not_empty_string
          - name: Currency
            description: The currency of the transaction.
            tests:
              - dbt_utils.not_empty_string
          - name: "User Description"
            description: A user-provided description of the transaction.
          - name: Memo
            description: A user-provided memo for the transaction.
          - name: Classification
            description: The classification of the transaction.
          - name: "Split Type"
            description: The type of split for the transaction.

  - name: revolut
    database: "{{ 'local' if target.name == 'local' else 'etl' }}"
    schema: main
    tables:
      - name: raw_revolut__personal
        description: Raw transaction data from Revolut (Personal).
        columns:
          - name: Type
            description: The type of the transaction.
            tests:
              - source_accepted_values:
                  values:
                    [
                      "ATM",
                      "CARD_PAYMENT",
                      "CARD_REFUND",
                      "CHARGE",
                      "EXCHANGE",
                      "FEE",
                      "INTEREST",
                      "REFUND",
                      "REV_PAYMENT",
                      "REWARD",
                      "TAX",
                      "TEMP_BLOCK",
                      "TOPUP",
                      "TRANSFER",
                      "Card Payment",
                      "Card Refund",
                      "Charge",
                      "Exchange",
                      "Interest",
                      "Rev Payment",
                      "Topup",
                      "Transfer",
                    ]
          - name: Product
            description: The product associated with the transaction.
            tests:
              - source_accepted_values:
                  values: ["Current", "Pocket", "Savings", "Deposit"]
          - name: Started Date
            description: The date the transaction was started.
            tests:
              - not_null
          - name: Completed Date
            description: The date the transaction was completed.
            tests:
              - not_null:
                  config:
                    where: "state = 'COMPLETED'"
          - name: Description
            description: The description of the transaction.
            tests:
              - not_null
          - name: Amount
            description: The amount of the transaction.
            tests:
              - not_null
          - name: Fee
            description: The fee associated with the transaction.
            tests:
              - not_null
          - name: Currency
            description: The currency of the transaction.
            tests:
              - not_null
          - name: State
            description: The state of the transaction.
            tests:
              - source_accepted_values:
                  values: ["COMPLETED", "REVERTED", "PENDING"]
          - name: Balance
            description: The balance after the transaction.
            tests:
              - not_null
      - name: raw_revolut__joint
        description: Raw transaction data from Revolut (Joint).
        columns:
          - name: Type
            description: The type of the transaction.
            tests:
              - source_accepted_values:
                  values:
                    [
                      "ATM",
                      "CARD_PAYMENT",
                      "CARD_REFUND",
                      "CHARGE",
                      "EXCHANGE",
                      "FEE",
                      "INTEREST",
                      "REFUND",
                      "REV_PAYMENT",
                      "REWARD",
                      "TAX",
                      "TEMP_BLOCK",
                      "TOPUP",
                      "TRANSFER",
                      "Card Payment",
                      "Card Refund",
                      "Charge",
                      "Exchange",
                      "Interest",
                      "Rev Payment",
                      "Topup",
                      "Transfer",
                    ]
          - name: Product
            description: The product associated with the transaction.
            tests:
              - source_accepted_values:
                  values: ["Current", "Pocket", "Savings", "Deposit"]
          - name: Started Date
            description: The date the transaction was started.
            tests:
              - not_null
          - name: Completed Date
            description: The date the transaction was completed.
            tests:
              - not_null:
                  config:
                    where: "state = 'COMPLETED'"
          - name: Description
            description: The description of the transaction.
            tests:
              - not_null
          - name: Amount
            description: The amount of the transaction.
            tests:
              - not_null
          - name: Fee
            description: The fee associated with the transaction.
            tests:
              - not_null
          - name: Currency
            description: The currency of the transaction.
            tests:
              - not_null
          - name: State
            description: The state of the transaction.
            tests:
              - source_accepted_values:
                  values: ["COMPLETED", "REVERTED", "PENDING"]
          - name: Balance
            description: The balance after the transaction.
            tests:
              - not_null
      - name: raw_revolut__spouse
        description: Raw transaction data from Revolut (Spouse).
        columns:
          - name: Type
            description: The type of the transaction.
            tests:
              - source_accepted_values:
                  values:
                    [
                      "ATM",
                      "CARD_PAYMENT",
                      "CARD_REFUND",
                      "CHARGE",
                      "EXCHANGE",
                      "FEE",
                      "INTEREST",
                      "REFUND",
                      "REV_PAYMENT",
                      "REWARD",
                      "TAX",
                      "TEMP_BLOCK",
                      "TOPUP",
                      "TRANSFER",
                      "Card Payment",
                      "Card Refund",
                      "Charge",
                      "Exchange",
                      "Interest",
                      "Rev Payment",
                      "Topup",
                      "Transfer",
                    ]
          - name: Product
            description: The product associated with the transaction.
            tests:
              - source_accepted_values:
                  values: ["Current", "Pocket", "Savings", "Deposit"]
          - name: Started Date
            description: The date the transaction was started.
            tests:
              - not_null
          - name: Completed Date
            description: The date the transaction was completed.
            tests:
              - not_null:
                  config:
                    where: "state = 'COMPLETED'"
          - name: Description
            description: The description of the transaction.
            tests:
              - not_null
          - name: Amount
            description: The amount of the transaction.
            tests:
              - not_null
          - name: Fee
            description: The fee associated with the transaction.
            tests:
              - not_null
          - name: Currency
            description: The currency of the transaction.
            tests:
              - not_null
          - name: State
            description: The state of the transaction.
            tests:
              - source_accepted_values:
                  values: ["COMPLETED", "REVERTED", "PENDING"]
          - name: Balance
            description: The balance after the transaction.
            tests:
              - not_null
