site_name: Budget DBT Wiki
site_dir: site
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Loading Process: loading.md
  - dbt Transforms: transforms.md
  - Manual Review and Cleanup: review.md
  - Streamlit Dashboard: dashboard.md
  - dbt Documentation: dbt.md
