name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  issues: 'write'
  pull-requests: 'write'

jobs:
  dbt_test:
    name: Run DBT Tests
    runs-on: ubuntu-latest
    env:
      DBT_PROJECT_DIR: dbt
      DBT_PROFILES_DIR: dbt
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync

      - name: Run local tests
        run: make test-local

      - name: Compute coverage
        id: coverage
        run: |
          doc_coverage=$(make -s doc-coverage)
          test_coverage=$(make -s test-coverage)
          echo "doc_coverage<<EOF" >> $GITHUB_OUTPUT
          echo "$doc_coverage" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "test_coverage<<EOF" >> $GITHUB_OUTPUT
          echo "$test_coverage" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## DBT Coverage Report

            ### Documentation Coverage
            
            ${{ steps.coverage.outputs.doc_coverage }}

            ### Test Coverage
            ${{ steps.coverage.outputs.test_coverage }}

  dbt_project_evaluator:
    name: Run DBT Project Evaluator
    runs-on: ubuntu-latest
    env:
      DBT_PROJECT_DIR: dbt
      DBT_PROFILES_DIR: dbt
      DBT_PROJECT_EVALUATOR_SEVERITY: error
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync

      - name: Setup local database
        run: |
          make test-local

      - name: Run project evaluator
        run: |
          make dbt-eval
